### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by o1gac** [sgiurgiu/DefaultAudioChanger#2]
Hi,

I would like to help you to transform this project into a product if you want. Please dont get me wrong, I've no commercial concerns on this. I was searching an app like this for a while because its very very useful if you're a gamer and have a headset with a sound card embeded into it.

Adding a new and fancy UI, some useful tweaks (OSD notifications etc.) and making a website for this project would be nice :) let me know if you're interested.

**Comment by sgiurgiu** [comment]
What do you have in mind? Are there any similar UIs out there that you'd consider appropriate for this kind of tool?

**Comment by o1gac** [comment]
Discord's app and overlay UI is nice and could be a sample. I could design the ui for you and share my ideas about new features for this app. Also we could make a marketing kit(logo, website etc.)

You can contact me: olgacdolek[at]yahoo.com
